/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CSVLoaderDialog.java
 *
 * Created on Feb 12, 2013, 11:24:42 AM
 */
package org.glotaran.csvdataloader;

import java.awt.Component;
import java.awt.LayoutManager;
import java.io.File;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.SpinnerNumberModel;
import org.ujmp.gui.panels.MatrixTableEditorPanel;

/**
 *
 * @author Sergey
 */
public class CSVLoaderDialog extends javax.swing.JPanel {

    /**
     * Creates new form CSVLoaderDialog
     */
    public CSVLoaderDialog() {
        initComponents();
    }

    public CSVLoaderDialog(MatrixTableEditorPanel matixEditor) {
        initComponents();
        jpMatrixEditor.add(matixEditor);
        for (Component comp : jPLifetimeDensityMapSettings.getComponents()) {
            comp.setVisible(cbLifetimeDensityMap.isSelected());
        }
        jPLifetimeDensityMapSettings.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jRadioButton1 = new javax.swing.JRadioButton();
        JRBGDelimiter = new javax.swing.ButtonGroup();
        jpMatrixEditor = new javax.swing.JPanel();
        cbLabelsInRows = new javax.swing.JCheckBox();
        cbLabelsInColums = new javax.swing.JCheckBox();
        jpCalibration = new javax.swing.JPanel();
        cbWaveCalbration = new javax.swing.JCheckBox();
        rbLoadFromFile = new javax.swing.JRadioButton();
        tfFilename = new javax.swing.JTextField();
        bOpenFile = new javax.swing.JButton();
        cbspectraInRows = new javax.swing.JCheckBox();
        jPSkip = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spSkipRows = new javax.swing.JSpinner();
        spSkipColums = new javax.swing.JSpinner();
        jPEnableLifetimeDensityMap = new javax.swing.JPanel();
        cbLifetimeDensityMap = new javax.swing.JCheckBox();
        jPLifetimeDensityMapSettings = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jFTFFrom = new javax.swing.JFormattedTextField();
        jCBLinLogEnabeled = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFTFTo = new javax.swing.JFormattedTextField();
        jFTFLogFrom = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFTFLinearFraction = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jFTFLastLifetimeMult = new javax.swing.JFormattedTextField();
        jFTFTimepoints = new javax.swing.JFormattedTextField();
        jPSeparator = new javax.swing.JPanel();
        jRBComma = new javax.swing.JRadioButton();
        jRBSemicolon = new javax.swing.JRadioButton();
        jRBTab = new javax.swing.JRadioButton();
        jRBSpace = new javax.swing.JRadioButton();
        jTFOtherSeparator = new javax.swing.JTextField();
        jRBOther = new javax.swing.JRadioButton();

        jRadioButton1.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jRadioButton1.text")); // NOI18N

        setMinimumSize(new java.awt.Dimension(100, 100));

        jpMatrixEditor.setLayout(new java.awt.BorderLayout());

        cbLabelsInRows.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.cbLabelsInRows.text")); // NOI18N

        cbLabelsInColums.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.cbLabelsInColums.text")); // NOI18N

        jpCalibration.setLayout(new java.awt.GridBagLayout());

        cbWaveCalbration.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.cbWaveCalbration.text")); // NOI18N
        cbWaveCalbration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbWaveCalbrationActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jpCalibration.add(cbWaveCalbration, gridBagConstraints);

        rbLoadFromFile.setSelected(true);
        rbLoadFromFile.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.rbLoadFromFile.text")); // NOI18N
        rbLoadFromFile.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jpCalibration.add(rbLoadFromFile, gridBagConstraints);

        tfFilename.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfFilename.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.tfFilename.text")); // NOI18N
        tfFilename.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 153;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jpCalibration.add(tfFilename, gridBagConstraints);

        bOpenFile.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.bOpenFile.text")); // NOI18N
        bOpenFile.setEnabled(false);
        bOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOpenFileActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = -14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jpCalibration.add(bOpenFile, gridBagConstraints);

        cbspectraInRows.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.cbspectraInRows.text")); // NOI18N

        jPSkip.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jPSkip.border.title"))); // NOI18N
        jPSkip.setMinimumSize(new java.awt.Dimension(245, 22));
        jPSkip.setPreferredSize(new java.awt.Dimension(245, 40));
        jPSkip.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jLabel1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPSkip.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jLabel2.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPSkip.add(jLabel2, gridBagConstraints);

        spSkipRows.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        spSkipRows.setName(""); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPSkip.add(spSkipRows, gridBagConstraints);

        spSkipColums.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPSkip.add(spSkipColums, gridBagConstraints);

        jPEnableLifetimeDensityMap.setBackground(new java.awt.Color(223, 223, 223));
        jPEnableLifetimeDensityMap.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jPEnableLifetimeDensityMap.border.title"))); // NOI18N
        jPEnableLifetimeDensityMap.setLayout(new java.awt.GridBagLayout());

        cbLifetimeDensityMap.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.cbLifetimeDensityMap.text")); // NOI18N
        cbLifetimeDensityMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLifetimeDensityMapActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        jPEnableLifetimeDensityMap.add(cbLifetimeDensityMap, gridBagConstraints);

        jPLifetimeDensityMapSettings.setEnabled(false);

        jLabel4.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jLabel4.text")); // NOI18N

        jFTFFrom.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.####"))));
        jFTFFrom.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jFTFFrom.text")); // NOI18N
        jFTFFrom.setPreferredSize(new java.awt.Dimension(60, 19));

        jCBLinLogEnabeled.setSelected(true);
        jCBLinLogEnabeled.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jCBLinLogEnabeled.text")); // NOI18N
        jCBLinLogEnabeled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBLinLogEnabeledActionPerformed(evt);
            }
        });

        jLabel5.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jLabel5.text")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jLabel6.text")); // NOI18N

        jFTFTo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.####"))));
        jFTFTo.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jFTFTo.text")); // NOI18N
        jFTFTo.setPreferredSize(new java.awt.Dimension(60, 19));

        jFTFLogFrom.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.####"))));
        jFTFLogFrom.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jFTFLogFrom.text")); // NOI18N
        jFTFLogFrom.setPreferredSize(new java.awt.Dimension(60, 19));

        jLabel3.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jLabel3.text")); // NOI18N

        jFTFLinearFraction.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFTFLinearFraction.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jFTFLinearFraction.text")); // NOI18N
        jFTFLinearFraction.setPreferredSize(new java.awt.Dimension(60, 19));

        jLabel7.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jLabel7.text")); // NOI18N

        jLabel8.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jLabel8.text")); // NOI18N

        jFTFLastLifetimeMult.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.####"))));
        jFTFLastLifetimeMult.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jFTFLastLifetimeMult.text")); // NOI18N
        jFTFLastLifetimeMult.setPreferredSize(new java.awt.Dimension(60, 19));

        jFTFTimepoints.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.####"))));
        jFTFTimepoints.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jFTFTimepoints.text")); // NOI18N
        jFTFTimepoints.setPreferredSize(new java.awt.Dimension(60, 19));

        javax.swing.GroupLayout jPLifetimeDensityMapSettingsLayout = new javax.swing.GroupLayout(jPLifetimeDensityMapSettings);
        jPLifetimeDensityMapSettings.setLayout(jPLifetimeDensityMapSettingsLayout);
        jPLifetimeDensityMapSettingsLayout.setHorizontalGroup(
            jPLifetimeDensityMapSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLifetimeDensityMapSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPLifetimeDensityMapSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPLifetimeDensityMapSettingsLayout.createSequentialGroup()
                        .addGroup(jPLifetimeDensityMapSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPLifetimeDensityMapSettingsLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPLifetimeDensityMapSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFTFTo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFTFFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFTFTimepoints, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPLifetimeDensityMapSettingsLayout.createSequentialGroup()
                        .addGroup(jPLifetimeDensityMapSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPLifetimeDensityMapSettingsLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFTFLinearFraction, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCBLinLogEnabeled)
                            .addComponent(jLabel6)
                            .addComponent(jFTFLogFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jFTFLastLifetimeMult, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 25, Short.MAX_VALUE))))
        );
        jPLifetimeDensityMapSettingsLayout.setVerticalGroup(
            jPLifetimeDensityMapSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPLifetimeDensityMapSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPLifetimeDensityMapSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPLifetimeDensityMapSettingsLayout.createSequentialGroup()
                        .addGroup(jPLifetimeDensityMapSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFTFFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPLifetimeDensityMapSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jFTFTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5))
                    .addComponent(jFTFTimepoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jCBLinLogEnabeled)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFTFLogFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPLifetimeDensityMapSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jFTFLinearFraction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFTFLastLifetimeMult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPEnableLifetimeDensityMap.add(jPLifetimeDensityMapSettings, gridBagConstraints);

        jPSeparator.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jPSeparator.border.title"))); // NOI18N
        jPSeparator.setPreferredSize(new java.awt.Dimension(380, 40));
        jPSeparator.setLayout(new java.awt.GridBagLayout());

        JRBGDelimiter.add(jRBComma);
        jRBComma.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jRBComma.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPSeparator.add(jRBComma, gridBagConstraints);

        JRBGDelimiter.add(jRBSemicolon);
        jRBSemicolon.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jRBSemicolon.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPSeparator.add(jRBSemicolon, gridBagConstraints);

        JRBGDelimiter.add(jRBTab);
        jRBTab.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jRBTab.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPSeparator.add(jRBTab, gridBagConstraints);

        JRBGDelimiter.add(jRBSpace);
        jRBSpace.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jRBSpace.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPSeparator.add(jRBSpace, gridBagConstraints);

        jTFOtherSeparator.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jTFOtherSeparator.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPSeparator.add(jTFOtherSeparator, gridBagConstraints);

        JRBGDelimiter.add(jRBOther);
        jRBOther.setText(org.openide.util.NbBundle.getMessage(CSVLoaderDialog.class, "CSVLoaderDialog.jRBOther.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPSeparator.add(jRBOther, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPEnableLifetimeDensityMap, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbLabelsInColums)
                            .addComponent(cbspectraInRows, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpCalibration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbLabelsInRows)
                    .addComponent(jPSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jpMatrixEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPSkip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(311, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPSkip, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPSeparator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbLabelsInRows)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbLabelsInColums)
                                .addGap(2, 2, 2)
                                .addComponent(cbspectraInRows))
                            .addComponent(jpCalibration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPEnableLifetimeDensityMap, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jpMatrixEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbWaveCalbrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbWaveCalbrationActionPerformed
        Component[] components = jpCalibration.getComponents();
        for (int i = 0; i < components.length; i++) {
            components[i].setEnabled(cbWaveCalbration.isSelected());
        }
        cbWaveCalbration.setEnabled(true);
    }//GEN-LAST:event_cbWaveCalbrationActionPerformed

    private void bOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOpenFileActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Select file with ...");
        chooser.setMultiSelectionEnabled(false);
//        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            tfFilename.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_bOpenFileActionPerformed

    private void cbLifetimeDensityMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLifetimeDensityMapActionPerformed
//        for (Component comp : jPLifetimeDensityMapSettings.getComponents()) {
//            comp.setVisible(cbLifetimeDensityMap.isSelected());
//        }
//        jPLifetimeDensityMapSettings.updateUI();
    }//GEN-LAST:event_cbLifetimeDensityMapActionPerformed

    private void jCBLinLogEnabeledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBLinLogEnabeledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBLinLogEnabeledActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup JRBGDelimiter;
    private javax.swing.JButton bOpenFile;
    private javax.swing.JCheckBox cbLabelsInColums;
    private javax.swing.JCheckBox cbLabelsInRows;
    private javax.swing.JCheckBox cbLifetimeDensityMap;
    private javax.swing.JCheckBox cbWaveCalbration;
    private javax.swing.JCheckBox cbspectraInRows;
    private javax.swing.JCheckBox jCBLinLogEnabeled;
    private javax.swing.JFormattedTextField jFTFFrom;
    private javax.swing.JFormattedTextField jFTFLastLifetimeMult;
    private javax.swing.JFormattedTextField jFTFLinearFraction;
    private javax.swing.JFormattedTextField jFTFLogFrom;
    private javax.swing.JFormattedTextField jFTFTimepoints;
    private javax.swing.JFormattedTextField jFTFTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPEnableLifetimeDensityMap;
    private javax.swing.JPanel jPLifetimeDensityMapSettings;
    private javax.swing.JPanel jPSeparator;
    private javax.swing.JPanel jPSkip;
    private javax.swing.JRadioButton jRBComma;
    private javax.swing.JRadioButton jRBOther;
    private javax.swing.JRadioButton jRBSemicolon;
    private javax.swing.JRadioButton jRBSpace;
    private javax.swing.JRadioButton jRBTab;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTFOtherSeparator;
    private javax.swing.JPanel jpCalibration;
    private javax.swing.JPanel jpMatrixEditor;
    private javax.swing.JRadioButton rbLoadFromFile;
    private javax.swing.JSpinner spSkipColums;
    private javax.swing.JSpinner spSkipRows;
    private javax.swing.JTextField tfFilename;
    // End of variables declaration//GEN-END:variables

    public boolean isLabelsInColums() {
        if (isSpectraInRows()) {
            return cbLabelsInRows.isSelected();
        } else {
            return cbLabelsInColums.isSelected();
        }
    }

    public boolean isLabelsInRows() {
        if (isSpectraInRows()) {
            return cbLabelsInColums.isSelected();
        } else {
            return cbLabelsInRows.isSelected();
        }
    }

    public boolean isWaveCalbrationEnabled() {
        return cbWaveCalbration.isSelected();
    }

    public boolean isSpectraInRows() {
        return cbspectraInRows.isSelected();
    }

    public String getFilename() {
        return tfFilename.getText();
    }

    public int getSkipRows() {
        return ((SpinnerNumberModel) spSkipRows.getModel()).getNumber().intValue();
    }

    public int getSkipColums() {
        return ((SpinnerNumberModel) spSkipColums.getModel()).getNumber().intValue();
    }

    boolean isLifetimeDensityMap() {
        return cbLifetimeDensityMap.isSelected();
    }

    public double getFrom() {
        return Double.valueOf(jFTFFrom.getText());
    }

    public double getLinearFraction() {
        return Double.valueOf(jFTFLinearFraction.getText());
    }

    public double getLogFrom() {
        return Double.valueOf(jFTFLogFrom.getText());
    }

    public double getLastLifetimeMult() {
        return Double.valueOf(jFTFLastLifetimeMult.getText());
    }

    public int getTimepoints() {
        Integer jFTFTimepointsValue;
        try {
            jFTFTimepointsValue = Integer.valueOf(jFTFTimepoints.getText());
        } catch (Exception e) {
            jFTFTimepointsValue = 1000;
        }
        return (int) jFTFTimepointsValue;
    }

    public double getTo() {
        return Double.valueOf(jFTFTo.getText());
    }

    public boolean isLinLogEnabeled() {
        return jCBLinLogEnabeled.isSelected();
    }

}
