/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SelectedMultiTracesPanel.java
 *
 * Created on Mar 25, 2010, 3:22:01 PM
 */

package org.glotaran.core.resultdisplayers.global.spec;

import java.awt.GridBagLayout;
import java.awt.GridLayout;
import javax.swing.JPanel;

/**
 *
 * @author jsg210
 */
public class SelectedMultiTracesPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    /** Creates new form SelectedMultiTracesPanel */
    public SelectedMultiTracesPanel() {
        initComponents();
        jPSelectedTracesContainer.setLayout(new GridLayout(2, 2));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPSelectedTracesContainer = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPSelectedTracesContainerLayout = new javax.swing.GroupLayout(jPSelectedTracesContainer);
        jPSelectedTracesContainer.setLayout(jPSelectedTracesContainerLayout);
        jPSelectedTracesContainerLayout.setHorizontalGroup(
            jPSelectedTracesContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        jPSelectedTracesContainerLayout.setVerticalGroup(
            jPSelectedTracesContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPSelectedTracesContainer);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getjPSelectedTracesContainer() {
        return jPSelectedTracesContainer;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel jPSelectedTracesContainer;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
