/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OutputPanel.java
 *
 * Created on Feb 16, 2010, 10:41:06 AM
 */
package org.glotaran.core.ui.visualmodelling.components;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.filechooser.FileSystemView;
import org.glotaran.core.models.gta.GtaOutput;
import org.openide.filesystems.FileObject;
import org.openide.filesystems.FileUtil;

/**
 *
 * @author jsg210
 */
public class OutputPanel
        extends JPanel {

    private static final long serialVersionUID = 1;
    private GtaOutput outputDO;
    private FileObject root;
    private String outputPath;

    public OutputPanel() {
        initComponents();
    }

    public OutputPanel(GtaOutput myNode, FileObject resultsFolder, PropertyChangeListener listn) {
        outputDO = myNode;
        root = resultsFolder;
        initComponents();
        outputPath = outputDO.getOutputPath();
        if (outputPath!=null && !outputPath.isEmpty()){
            jTFFileName.setText(outputPath);
        } else {
            jTFFileName.setText(" ... please specify output path ... ");
        }
        if (outputDO.isGenerateErrorBars() != null) {
            jCCalculateErrors.setSelected(outputDO.isGenerateErrorBars());
        } else {
            jCCalculateErrors.setSelected(false);
        }
        addPropertyChangeListener(listn);        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSIterationsNum = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTFFileName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jCCalculateErrors = new javax.swing.JCheckBox();

        setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setText(org.openide.util.NbBundle.getMessage(OutputPanel.class, "OutputPanel.jLabel1.text")); // NOI18N

        jSIterationsNum.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        if (outputDO.getIterations() != null) {
            jSIterationsNum.getModel().setValue(Integer.parseInt(outputDO.getIterations()));
        } else {
            jSIterationsNum.getModel().setValue(0);
            outputDO.setIterations("0");
        }
        jSIterationsNum.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSIterationsNumStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSIterationsNum, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSIterationsNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.33;
        add(jPanel3, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel2.setText(org.openide.util.NbBundle.getMessage(OutputPanel.class, "OutputPanel.jLabel2.text")); // NOI18N

        jTFFileName.setEditable(false);
        jTFFileName.setText(org.openide.util.NbBundle.getMessage(OutputPanel.class, "OutputPanel.jTFFileName.text")); // NOI18N

        jButton1.setText(org.openide.util.NbBundle.getMessage(OutputPanel.class, "OutputPanel.jButton1.text")); // NOI18N
        jButton1.setMaximumSize(new java.awt.Dimension(25, 20));
        jButton1.setMinimumSize(new java.awt.Dimension(25, 20));
        jButton1.setPreferredSize(new java.awt.Dimension(25, 20));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFFileName, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.34;
        add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jCCalculateErrors.setBackground(new java.awt.Color(153, 255, 153));
        jCCalculateErrors.setText(org.openide.util.NbBundle.getMessage(OutputPanel.class, "OutputPanel.jCCalculateErrors.text")); // NOI18N
        jCCalculateErrors.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCCalculateErrorsStateChanged(evt);
            }
        });
        jCCalculateErrors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCCalculateErrorsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCCalculateErrors)
                .addContainerGap(343, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCCalculateErrors)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.33;
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FileSystemView fsv = new SingleRootFileSystemView(FileUtil.toFile(root));
        JFileChooser chooser = new JFileChooser(fsv);
        chooser.setDialogTitle("Select Output Folder ...");
        chooser.setMultiSelectionEnabled(false);
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File folder = chooser.getSelectedFile();
            outputPath = FileUtil.getRelativePath(root, FileUtil.toFileObject(folder));
            jTFFileName.setText(outputPath);
            outputDO.setOutputPath(outputPath);
            firePropertyChange("modelChanged", null, null);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jSIterationsNumStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSIterationsNumStateChanged
        outputDO.setIterations(jSIterationsNum.getModel().getValue().toString());
        firePropertyChange("modelChanged", null, null);
    }//GEN-LAST:event_jSIterationsNumStateChanged

    private void jCCalculateErrorsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCCalculateErrorsStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jCCalculateErrorsStateChanged

    private void jCCalculateErrorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCCalculateErrorsActionPerformed
        // TODO add your handling code here:
        outputDO.setGenerateErrorBars(jCCalculateErrors.isSelected());
        firePropertyChange("modelChanged", null, null);
    }//GEN-LAST:event_jCCalculateErrorsActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCCalculateErrors;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner jSIterationsNum;
    private javax.swing.JTextField jTFFileName;
    // End of variables declaration//GEN-END:variables
}
