//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.12 at 04:23:28 PM CEST 
//


package org.glotaran.core.models.sim;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lambdaMin" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="lambdaMax" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="lamdaStep" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="timeMin" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="timeMax" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="timeStep" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="lowerLinearTimeBound" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="upperLinearTimeBound" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="spectras" type="{http://glotaran.org/schema/SpectralModelSchema}Spectra" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="noiseType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="noiseAmplitude" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="noiseSeed" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="numberOfLogPoints" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lambdaMin",
    "lambdaMax",
    "lamdaStep",
    "timeMin",
    "timeMax",
    "timeStep",
    "lowerLinearTimeBound",
    "upperLinearTimeBound",
    "spectras",
    "noiseType",
    "noiseAmplitude",
    "noiseSeed",
    "numberOfLogPoints"
})
@XmlRootElement(name = "SpectralModelSpecification")
public class SpectralModelSpecification {

    protected double lambdaMin;
    protected double lambdaMax;
    protected double lamdaStep;
    protected double timeMin;
    protected double timeMax;
    protected double timeStep;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double lowerLinearTimeBound;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double upperLinearTimeBound;
    @XmlElement(nillable = true)
    protected List<Spectra> spectras;
    @XmlElement(required = true, nillable = true)
    protected String noiseType;
    @XmlElement(required = true, type = Double.class, nillable = true)
    protected Double noiseAmplitude;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer noiseSeed;
    @XmlElement(required = true, type = Integer.class, nillable = true)
    protected Integer numberOfLogPoints;

    /**
     * Gets the value of the lambdaMin property.
     * 
     */
    public double getLambdaMin() {
        return lambdaMin;
    }

    /**
     * Sets the value of the lambdaMin property.
     * 
     */
    public void setLambdaMin(double value) {
        this.lambdaMin = value;
    }

    /**
     * Gets the value of the lambdaMax property.
     * 
     */
    public double getLambdaMax() {
        return lambdaMax;
    }

    /**
     * Sets the value of the lambdaMax property.
     * 
     */
    public void setLambdaMax(double value) {
        this.lambdaMax = value;
    }

    /**
     * Gets the value of the lamdaStep property.
     * 
     */
    public double getLamdaStep() {
        return lamdaStep;
    }

    /**
     * Sets the value of the lamdaStep property.
     * 
     */
    public void setLamdaStep(double value) {
        this.lamdaStep = value;
    }

    /**
     * Gets the value of the timeMin property.
     * 
     */
    public double getTimeMin() {
        return timeMin;
    }

    /**
     * Sets the value of the timeMin property.
     * 
     */
    public void setTimeMin(double value) {
        this.timeMin = value;
    }

    /**
     * Gets the value of the timeMax property.
     * 
     */
    public double getTimeMax() {
        return timeMax;
    }

    /**
     * Sets the value of the timeMax property.
     * 
     */
    public void setTimeMax(double value) {
        this.timeMax = value;
    }

    /**
     * Gets the value of the timeStep property.
     * 
     */
    public double getTimeStep() {
        return timeStep;
    }

    /**
     * Sets the value of the timeStep property.
     * 
     */
    public void setTimeStep(double value) {
        this.timeStep = value;
    }

    /**
     * Gets the value of the lowerLinearTimeBound property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLowerLinearTimeBound() {
        return lowerLinearTimeBound;
    }

    /**
     * Sets the value of the lowerLinearTimeBound property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLowerLinearTimeBound(Double value) {
        this.lowerLinearTimeBound = value;
    }

    /**
     * Gets the value of the upperLinearTimeBound property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getUpperLinearTimeBound() {
        return upperLinearTimeBound;
    }

    /**
     * Sets the value of the upperLinearTimeBound property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setUpperLinearTimeBound(Double value) {
        this.upperLinearTimeBound = value;
    }

    /**
     * Gets the value of the spectras property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spectras property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpectras().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Spectra }
     * 
     * 
     */
    public List<Spectra> getSpectras() {
        if (spectras == null) {
            spectras = new ArrayList<Spectra>();
        }
        return this.spectras;
    }

    /**
     * Gets the value of the noiseType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoiseType() {
        return noiseType;
    }

    /**
     * Sets the value of the noiseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoiseType(String value) {
        this.noiseType = value;
    }

    /**
     * Gets the value of the noiseAmplitude property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getNoiseAmplitude() {
        return noiseAmplitude;
    }

    /**
     * Sets the value of the noiseAmplitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setNoiseAmplitude(Double value) {
        this.noiseAmplitude = value;
    }

    /**
     * Gets the value of the noiseSeed property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNoiseSeed() {
        return noiseSeed;
    }

    /**
     * Sets the value of the noiseSeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNoiseSeed(Integer value) {
        this.noiseSeed = value;
    }

    /**
     * Gets the value of the numberOfLogPoints property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfLogPoints() {
        return numberOfLogPoints;
    }

    /**
     * Sets the value of the numberOfLogPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfLogPoints(Integer value) {
        this.numberOfLogPoints = value;
    }

}
