//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.11 at 09:14:57 PM CEST 
//


package org.glotaran.core.models.gta;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GtaSimulationContainer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GtaSimulationContainer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="layout" type="{http://glotaran.org/schema/GlobalAndTargetAnalysisSchema}GtaLayout"/>
 *         &lt;element name="simulationInputRef" type="{http://glotaran.org/schema/GlobalAndTargetAnalysisSchema}GtaSimulationInputRef" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GtaSimulationContainer", propOrder = {
    "id",
    "layout",
    "simulationInputRef"
})
public class GtaSimulationContainer {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected GtaLayout layout;
    @XmlElement(nillable = true)
    protected List<GtaSimulationInputRef> simulationInputRef;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the layout property.
     * 
     * @return
     *     possible object is
     *     {@link GtaLayout }
     *     
     */
    public GtaLayout getLayout() {
        return layout;
    }

    /**
     * Sets the value of the layout property.
     * 
     * @param value
     *     allowed object is
     *     {@link GtaLayout }
     *     
     */
    public void setLayout(GtaLayout value) {
        this.layout = value;
    }

    /**
     * Gets the value of the simulationInputRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the simulationInputRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSimulationInputRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GtaSimulationInputRef }
     * 
     * 
     */
    public List<GtaSimulationInputRef> getSimulationInputRef() {
        if (simulationInputRef == null) {
            simulationInputRef = new ArrayList<GtaSimulationInputRef>();
        }
        return this.simulationInputRef;
    }

}
