//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.09 at 03:30:53 PM CEST 
//


package org.glotaran.core.models.gta;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.glotaran.core.models.gta package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.glotaran.core.models.gta
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GtaProjectScheme }
     * 
     */
    public GtaProjectScheme createGtaProjectScheme() {
        return new GtaProjectScheme();
    }

    /**
     * Create an instance of {@link GtaRelation }
     * 
     */
    public GtaRelation createGtaRelation() {
        return new GtaRelation();
    }

    /**
     * Create an instance of {@link GtaLinkCLP }
     * 
     */
    public GtaLinkCLP createGtaLinkCLP() {
        return new GtaLinkCLP();
    }

    /**
     * Create an instance of {@link GtaModelReference }
     * 
     */
    public GtaModelReference createGtaModelReference() {
        return new GtaModelReference();
    }

    /**
     * Create an instance of {@link GtaModelDifferences }
     * 
     */
    public GtaModelDifferences createGtaModelDifferences() {
        return new GtaModelDifferences();
    }

    /**
     * Create an instance of {@link GtaSimulationContainer }
     * 
     */
    public GtaSimulationContainer createGtaSimulationContainer() {
        return new GtaSimulationContainer();
    }

    /**
     * Create an instance of {@link GtaSimulationInputRef }
     * 
     */
    public GtaSimulationInputRef createGtaSimulationInputRef() {
        return new GtaSimulationInputRef();
    }

    /**
     * Create an instance of {@link GtaDatasetScaling }
     * 
     */
    public GtaDatasetScaling createGtaDatasetScaling() {
        return new GtaDatasetScaling();
    }

    /**
     * Create an instance of {@link GtaLayout }
     * 
     */
    public GtaLayout createGtaLayout() {
        return new GtaLayout();
    }

    /**
     * Create an instance of {@link GtaOutput }
     * 
     */
    public GtaOutput createGtaOutput() {
        return new GtaOutput();
    }

    /**
     * Create an instance of {@link GtaDatasetContainer }
     * 
     */
    public GtaDatasetContainer createGtaDatasetContainer() {
        return new GtaDatasetContainer();
    }

    /**
     * Create an instance of {@link GtaChangesModel }
     * 
     */
    public GtaChangesModel createGtaChangesModel() {
        return new GtaChangesModel();
    }

    /**
     * Create an instance of {@link GtaDataset }
     * 
     */
    public GtaDataset createGtaDataset() {
        return new GtaDataset();
    }

    /**
     * Create an instance of {@link GtaModelDiffContainer }
     * 
     */
    public GtaModelDiffContainer createGtaModelDiffContainer() {
        return new GtaModelDiffContainer();
    }

    /**
     * Create an instance of {@link GtaModelDiffDO }
     * 
     */
    public GtaModelDiffDO createGtaModelDiffDO() {
        return new GtaModelDiffDO();
    }

    /**
     * Create an instance of {@link GtaConnection }
     * 
     */
    public GtaConnection createGtaConnection() {
        return new GtaConnection();
    }

}
