/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * selectDataDialog.java
 *
 * Created on May 18, 2010, 3:44:50 PM
 */

package org.glotaran.core.main.common;

/**
 *
 * @author jsg210
 */
public class SelectDataDialog extends javax.swing.JPanel {

    /** Creates new form selectDataDialog */
    public SelectDataDialog() {
        initComponents();
        dimensionPanel2.setPanName("Dimension 2(Time)");
        dimensionPanel1.setPanName("Dimension 1(Waves)");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dimensionPanel1 = new org.glotaran.core.main.common.DimensionPanel();
        dimensionPanel2 = new org.glotaran.core.main.common.DimensionPanel();

        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(dimensionPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(dimensionPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.glotaran.core.main.common.DimensionPanel dimensionPanel1;
    private org.glotaran.core.main.common.DimensionPanel dimensionPanel2;
    // End of variables declaration//GEN-END:variables

    public double getDim1From(){
        return dimensionPanel1.getDimFrom();
    }
    public double getDim1To(){
        return dimensionPanel1.getDimTo();
    }
    public double getDim2From(){
        return dimensionPanel2.getDimFrom();
    }
    public double getDim2To(){
        return dimensionPanel2.getDimTo();
    }

    @Override
    public void setEnabled(boolean enabled) {
        for (int i = 0; i < getComponentCount(); i++) {
            getComponent(i).setEnabled(enabled);
        }
    }
}
