//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.19 at 01:52:24 PM CET 
//
package org.glotaran.core.models.tgd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for TgdDatasetEntry complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TgdDatasetEntry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="datasetName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="thresholdMax" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="thresholdMin" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TgdDatasetEntry", propOrder = {
    "datasetName",
    "thresholdMax",
    "thresholdMin"
})
public class TgdDatasetEntry {

    @XmlElement(required = true)
    protected String datasetName;
    protected double thresholdMax;
    protected double thresholdMin;

    /**
     * Gets the value of the datasetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatasetName() {
        return datasetName;
    }

    /**
     * Sets the value of the datasetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatasetName(String value) {
        this.datasetName = value;
    }

    /**
     * Gets the value of the thresholdMax property.
     * 
     */
    public double getThresholdMax() {
        return thresholdMax;
    }

    /**
     * Sets the value of the thresholdMax property.
     * 
     */
    public void setThresholdMax(double value) {
        this.thresholdMax = value;
    }

    /**
     * Gets the value of the thresholdMin property.
     * 
     */
    public double getThresholdMin() {
        return thresholdMin;
    }

    /**
     * Sets the value of the thresholdMin property.
     * 
     */
    public void setThresholdMin(double value) {
        this.thresholdMin = value;
    }
}
