/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.glotaran.comparetracesfx.swingcomponents;

import java.io.IOException;
import java.net.URL;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import static javafx.scene.input.DataFormat.URL;
import javafx.scene.paint.Color;
import org.glotaran.comparetracesfx.fxcomponents.CompareTracesCseneController;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Exceptions;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.glotaran.comparetracesfx.swingcomponents//CompareTraces//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "CompareTracesTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "org.glotaran.comparetracesfx.swingcomponents.CompareTracesTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_CompareTracesAction",
        preferredID = "CompareTracesTopComponent"
)
@Messages({
    "CTL_CompareTracesAction=CompareTraces",
    "CTL_CompareTracesTopComponent=CompareTraces Window",
    "HINT_CompareTracesTopComponent=This is a CompareTraces window"
})
public final class CompareTracesTopComponent extends TopComponent {

    JFXPanel fxPanel;
    
    public CompareTracesTopComponent() {
        initComponents();
        setName(Bundle.CTL_CompareTracesTopComponent());
        setToolTipText(Bundle.HINT_CompareTracesTopComponent());
        fxPanel = new JFXPanel();
        add(fxPanel);
        Platform.setImplicitExit(false);
        Platform.runLater(()-> createScene());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    private void createScene() {

        try {
            URL url = getClass().getResource("/fxml/CompareTracesCsene.fxml");
            Parent root = FXMLLoader.load(url);
            Scene scene = new Scene(root, Color.LIGHTBLUE);
            fxPanel.setScene(scene);
        } catch (IOException ex) {
            Exceptions.printStackTrace(ex);
        }
    }
}
