//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.16 at 02:40:05 PM CET 
//
package org.glotaran.core.models.tgm;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dat" type="{http://www.nat.vu.nl/~jsnel/Schema/TgmSchema}Dat"/>
 *         &lt;element name="panelStates" type="{http://www.w3.org/2001/XMLSchema}boolean" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dat",
    "panelStates"
})
@XmlRootElement(name = "tgm")
public class Tgm {

    @XmlElement(required = true, nillable = true)
    protected Dat dat;
    @XmlElement(required = true, nillable = true)
    protected List<Boolean> panelStates;

    /**
     * Gets the value of the dat property.
     * 
     * @return
     *     possible object is
     *     {@link Dat }
     *     
     */
    public Dat getDat() {
        return dat;
    }

    /**
     * Sets the value of the dat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dat }
     *     
     */
    public void setDat(Dat value) {
        this.dat = value;
    }

    /**
     * Gets the value of the panelStates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the panelStates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPanelStates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Boolean }
     * 
     * 
     */
    public List<Boolean> getPanelStates() {
        if (panelStates == null) {
            panelStates = new ArrayList<Boolean>();
        }
        return this.panelStates;
    }
}
