/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * selectDataDialog.java
 *
 * Created on May 18, 2010, 3:44:50 PM
 */

package org.glotaran.core.main.common;

/**
 *
 * @author jsg210
 */
public class SelectDataDialog extends javax.swing.JPanel {

    /** Creates new form selectDataDialog */
    public SelectDataDialog() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPDim1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFDim1From = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFDim1To = new javax.swing.JTextField();
        jPDim2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTFDim2From = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFDim2To = new javax.swing.JTextField();

        jPDim1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(SelectDataDialog.class, "SelectDataDialog.jPDim1.border.title"))); // NOI18N
        jPDim1.setPreferredSize(new java.awt.Dimension(150, 93));

        jLabel1.setText(org.openide.util.NbBundle.getMessage(SelectDataDialog.class, "SelectDataDialog.jLabel1.text")); // NOI18N

        jTFDim1From.setText(org.openide.util.NbBundle.getMessage(SelectDataDialog.class, "SelectDataDialog.jTFDim1From.text")); // NOI18N
        jTFDim1From.setPreferredSize(new java.awt.Dimension(20, 19));

        jLabel2.setText(org.openide.util.NbBundle.getMessage(SelectDataDialog.class, "SelectDataDialog.jLabel2.text")); // NOI18N

        jTFDim1To.setText(org.openide.util.NbBundle.getMessage(SelectDataDialog.class, "SelectDataDialog.jTFDim1To.text")); // NOI18N
        jTFDim1To.setPreferredSize(new java.awt.Dimension(20, 19));

        javax.swing.GroupLayout jPDim1Layout = new javax.swing.GroupLayout(jPDim1);
        jPDim1.setLayout(jPDim1Layout);
        jPDim1Layout.setHorizontalGroup(
            jPDim1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDim1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDim1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPDim1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFDim1To, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(jTFDim1From, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
        );
        jPDim1Layout.setVerticalGroup(
            jPDim1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDim1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDim1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDim1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(jPDim1Layout.createSequentialGroup()
                        .addComponent(jTFDim1From, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFDim1To, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPDim2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(SelectDataDialog.class, "SelectDataDialog.jPDim2.border.title"))); // NOI18N
        jPDim2.setPreferredSize(new java.awt.Dimension(150, 93));

        jLabel3.setText(org.openide.util.NbBundle.getMessage(SelectDataDialog.class, "SelectDataDialog.jLabel3.text")); // NOI18N

        jTFDim2From.setText(org.openide.util.NbBundle.getMessage(SelectDataDialog.class, "SelectDataDialog.jTFDim2From.text")); // NOI18N
        jTFDim2From.setPreferredSize(new java.awt.Dimension(20, 19));

        jLabel4.setText(org.openide.util.NbBundle.getMessage(SelectDataDialog.class, "SelectDataDialog.jLabel4.text")); // NOI18N

        jTFDim2To.setText(org.openide.util.NbBundle.getMessage(SelectDataDialog.class, "SelectDataDialog.jTFDim2To.text")); // NOI18N
        jTFDim2To.setPreferredSize(new java.awt.Dimension(20, 19));

        javax.swing.GroupLayout jPDim2Layout = new javax.swing.GroupLayout(jPDim2);
        jPDim2.setLayout(jPDim2Layout);
        jPDim2Layout.setHorizontalGroup(
            jPDim2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDim2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDim2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPDim2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFDim2To, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(jTFDim2From, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
        );
        jPDim2Layout.setVerticalGroup(
            jPDim2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDim2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPDim2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFDim2From, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPDim2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFDim2To, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPDim2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jPDim1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPDim1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPDim2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPDim1;
    private javax.swing.JPanel jPDim2;
    private javax.swing.JTextField jTFDim1From;
    private javax.swing.JTextField jTFDim1To;
    private javax.swing.JTextField jTFDim2From;
    private javax.swing.JTextField jTFDim2To;
    // End of variables declaration//GEN-END:variables

    public double getDim1From(){
        return Double.parseDouble(jTFDim1From.getText());
    }
    public double getDim1To(){
        return Double.parseDouble(jTFDim1To.getText());
    }
    public double getDim2From(){
        return Double.parseDouble(jTFDim2From.getText());
    }
    public double getDim2To(){
        return Double.parseDouble(jTFDim2To.getText());
    }

    @Override
    public void setEnabled(boolean enabled) {
        for (int i = 0; i < getComponentCount(); i++) {
            getComponent(i).setEnabled(enabled);
        }
        for (int i = 0; i < jPDim1.getComponentCount(); i++) {
            jPDim1.getComponent(i).setEnabled(enabled);
        }
        for (int i = 0; i < jPDim2.getComponentCount(); i++) {
            jPDim2.getComponent(i).setEnabled(enabled);
        }
    }
}
